services:
  ai-service:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: vicobi-ai-service
    ports:
      - "8000:8000" 
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      API_PREFIX: ${API_PREFIX}
      VERSION: ${VERSION}
      ENVIRONMENT: ${ENVIRONMENT}
      DEBUG: ${DEBUG}
      MONGO_HOST: ${MONGO_HOST:-mongo}
      MONGO_PORT: ${MONGO_PORT:-27017}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      BEDROCK_MODEL_ID: ${BEDROCK_MODEL_ID}
      BEDROCK_TIMEOUT: ${BEDROCK_TIMEOUT:-60}
      BEDROCK_TEMPERATURE: ${BEDROCK_TEMPERATURE:-0.0}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      USER_POOL_ID: ${USER_POOL_ID}
      APP_CLIENT_ID: ${APP_CLIENT_ID}
      REGION: ${REGION}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      ALLOWED_METHODS: ${ALLOWED_METHODS:-GET,POST,PUT,DELETE,OPTIONS}
      ALLOWED_HEADERS: ${ALLOWED_HEADERS:-*}
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_COLLECTION_NAME: ${QDRANT_COLLECTION_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      mongo:
        condition: service_healthy
      qdrant:
        condition: service_healthy

  mongo:
    image: mongo:latest
    container_name: vicobi-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 10s
      
  qdrant:
    image: qdrant/qdrant:latest
    container_name: vicobi-qdrant
    ports:
      - "6333:6333"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/collections"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongo_data:
  qdrant_data: